name: Update Readme
on:
  workflow_dispatch: 
  schedule:
    - cron: "0 0 * * *"
jobs:
  wakatime:
    name: Wakatime
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          TIME_RANGE: all_time
          SHOW_TITLE: false
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          LANG_COUNT: 5
          COMMIT_MESSAGE: "📊 Wakatime update"
  github-activity:
    name: Github Activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "⚡Recent activity update"
          MAX_LINES: 3
